first_number = int(input("Enter the first number : "))
second_number = int(input("Enter the second number : "))
print("===== COMPARISON OPERATORS =====")
print(f"First Number          : {first_number}")
print(f"Second Number         : {second_number}")
print(f"Is First Number Equal to Second Number? : {first_number == second_number}")
print(f"Is First Number Not Equal to Second Number? : {first_number != second_number}")
print(f"Is First Number Greater than Second Number? : {first_number > second_number}")
print(f"Is First Number Less than Second Number? : {first_number < second_number}")
print(f"Is First Number Greater than or Equal to Second Number? : {first_number >= second_number}")
print(f"Is First Number Less than or Equal to Second Number? : {first_number <= second_number}")
print("===============================")