Name = input("Enter your name : ")
Age = input("Enter your age : ")
College = input("Enter your college name : ")
Dream_Job = input("Enter your dream job : ")
print(f"My name is {Name} \nI am {Age} years old \nI study in {College} \nMy dream job is {Dream_Job}")
# print(Name)
# print(Age)
# print(College)
# print(Dream_Job)