length = float(input("Enter the length of rectangle : "))
width = float(input("Enter the width of rectangle : "))
area = length * width
perimeter = 2 * (length + width)
print("===== RECTANGLE =====")
print(f"Length : {length}")
print(f"Width : {width}")
print(f"Area : {area}")
print(f"Perimeter : {perimeter}")
print("=====================")