name = input("Enter your name : ")
weight = float(input("Enter your weight in kg : "))
height = float(input("Enter your height in meters : "))
bmi = weight / (height ** 2)
print("===== BMI REPORT =======")
print(f"Name   : {name}")
print(f"Weight : {weight}")
print(f"Height : {height}")
print("--------------------------")
print(f"BMI    : {bmi:.2f}")
print("==========================")